M48
; DRILL file {KiCad 7.0.7-7.0.7~ubuntu22.04.1} date Fri 12 Jan 2024 04:25:40 PM +0530
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-12T16:25:40+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-7.0.7~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X4.7091Y-3.6962
X4.7091Y-3.9238
T0
M30
